### ISSUE TITLE
Incorrect resource ARNs due to invalid delimiter

### ISSUE THREAD

**Issue by Arvinje** [diogofcunha/api-gateway-auth-policy#3]
I noticed all generated resource ARNs follow this `arn:aws:execute-api:region:accountId:apiId:stage:verb:/resource` structure, which is an invalid one according to the AWS docs. This causes the generator to issue invalid policy documents. The correct delimiter between `apiId`, `stage`, `verb` and `resource` shall be a slash instead of a colon. 

Cheers

**Comment by diogofcunha** [comment]
Hey @Arvinje you're totally correct, It's fixed in versio 1.0.1

Thanks 🙂
